name: dynamic_env_switching_flutterfire
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: ^1.7.3
  binder: ^0.2.2
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.0
  email_validator: ^1.0.6
  equatable: ^1.2.5
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
